### ISSUE TITLE
spellchecker for email input [2:47pm]

### ISSUE THREAD

**Issue by frankcollins3** [frankcollins3/fill_container#181]
several times a day I type in: 
myemail@gmial.com ----->

EMAIL_INPUT:     me@gmail.com

in the onChange handler 
how to  create a regex that grabs characters between '@'  '.'
between the @ and the . that precedes email extension.

performed in case the user types:
me@gmial.com

Let value:string = event.target.value
if (charBtwnString.includes('g', 'm', 'a', 'i', 'l' && charBtwnString !== 'gmail') {
    
}

**strprbok() in C** is similar to the .includes() section trying to grab all characters

the onChange handler is part of dynamic UI that parses: 'username' || 'password' || 'age' etc:
done because every input does same thing. it just needs to conditionally render value to input and value to state based on param

**Comment by frankcollins3** [comment]
kind of confused why these expressions don't validate the condition:

https://github.com/frankcollins3/fill_container/assets/73137934/30c78b12-8dfc-4716-b1a3-7005f8d3b164

![Screen Shot 2023-06-10 at 4 47 14 PM](https://github.com/frankcollins3/fill_container/assets/73137934/ab00ab36-31f8-4edf-bf70-e4d5b2d17fb1)

**proposed approach:**
1:
.trim() check for whitespace.

[5:03pm]

**Comment by frankcollins3** [comment]
`console.log(`emailStr: ${emailString} ${typeof emailString} ${emailString.length}`)`

```
ERROR
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at inputOnChange (http://localhost:3000/static/js/bundle.js:3879:81)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:43734:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:43778:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:43835:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:43849:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:47993:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:48019:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:48030:9)
    at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:48039:7)
    at http://localhost:3000/static/js/bundle.js:48199:16
```

!str...
[5:12pm]

**Comment by frankcollins3** [comment]
WORKS! 

https://github.com/frankcollins3/fill_container/assets/73137934/49b11a9d-fabb-41dc-bb15-6a0fe27dbd35

```
    const inputOnChange = (event:any) => {
        let value:string = event.target.value
        if (inputType === 'username') {            
            inputHandler(event, SET_USERNAME_INPUT)
        }
        if (inputType === 'email') {
            const splitHelper = event.target.value.split('@.')

            let splitEmail:any = value.match(MsplitAtDot)

            if (splitEmail !== null) {
                const typoPromise = new Promise( (resolve, reject) => {
                    const matchedValue:string = splitEmail[0].replace(RdotAtEscape, '')
                    const premail:any = value.match(McharBeforeAt)
                    const emailNoAt:string = premail[0]
                    if (matchedValue?.includes('g') && matchedValue.includes('m') && matchedValue.includes('a') && matchedValue.includes('i') && matchedValue.includes('l') && matchedValue !== 'gmail') {
                        console.log('G M A I L in the string but it doesnt === GMAIL')
                        let remail:string = `${emailNoAt}@gmail.com`
                        SET_EMAIL_INPUT({payload: remail})                         
                    } else {
                        console.log(`GMAIL splitEmail ${splitEmail}`)
                    }                    
                }).then( (email) => {
                    console.log('email')
                    console.log(email)
                })
            } else {
                inputHandler(event, SET_EMAIL_INPUT)
            }
```

👎 problem: (if anyones watching lol)

in the video it last shows backspacing and pressing 'd' and backspace. 
I was pressing '.' the period character. 

The escape sequence that allows: me@gmail.com to become **@gmail.**
 then replace that to become **gmail** that replace is restricting the 

**proposed approach:**

1: first thought came to mind: allow the user to not submit the **.com** and handle appending in GraphQL
this may confuse the user that they can't interact with this input as they could another input.

2: can do the same thing client-side and append .com when:(i.e.)-> 
// user types this in:
1: **me@gmail**

**Comment by frankcollins3** [comment]
replace the: '.' period character with something other than .replace()
[6:42pm]

**Comment by frankcollins3** [comment]
```
            if (value[value.length-1] === '.') {
                let splitEmail:any = value.match(MsplitAtDot)
                console.log('splitEmail')
                console.log(splitEmail)
                if (splitEmail != null) {
                    const matchedValue:string = splitEmail[0]
                    const premail:any = value.match(McharBeforeAt)
                    const emailNoAt:string = premail[0]
                    console.log('matchedvalue')
                    console.log(matchedValue)

                    if (matchedValue?.includes('g') && matchedValue.includes('m') && matchedValue.includes('a') && matchedValue.includes('i') && matchedValue.includes('l') && matchedValue !== '@gmail.') {
                        setDontSet(true)
                        console.log('G M A I L in the string but it doesnt === GMAIL')
                        let remail:string = `${emailNoAt}gmail.com`
                        console.log('remail')
                        console.log(remail)
👎                         SET_EMAIL_INPUT( {payload: 'hey' } )                         
                    } 
                    else {
                        setDontSet(false)
                        inputHandler(event, SET_EMAIL_INPUT)
                    }
                }
            }
                        dontSet ? console.log('aaye') : inputHandler(event, SET_EMAIL_INPUT)
            }                

```

👎                         SET_EMAIL_INPUT( {payload: 'hey' } )                         // this doesn't set 

👎                         dontSet ? console.log('aaye') : inputHandler(event, SET_EMAIL_INPUT)
boolFlag-> true -> then the user is locked in the truthy block of the above ternary which restricts setting state

this behavior makes our input an unput
[7:10pm]

**Comment by frankcollins3** [comment]
WOW! 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 

setTimeout( () => SET_EMAIL_INPUT( {payload: remail } ), 2000) 

                    **if (matchedValue?.includes('g') && matchedValue.includes('m') && matchedValue.includes('a') && matchedValue.includes('i') && matchedValue.includes('l') && matchedValue !== '@gmail.') {
                        setDontSet(true)
                        console.log('G M A I L in the string but it doesnt === GMAIL')
                        let remail:string = `${emailNoAt}gmail.com`
                        console.log('remail')
                        console.log(remail)
                        setTimeout( () => SET_EMAIL_INPUT( {payload: remail } ), 500)                         
                        dontSet(false)
                    } 
                    else {
                        setDontSet(false)
                        inputHandler(event, SET_EMAIL_INPUT)
                    }
                }
            }
👎                         dontSet ? console.log('aaye') : inputHandler(event, SET_EMAIL_INPUT)
            }**             

[7:15pm]

**Comment by frankcollins3** [comment]
https://github.com/frankcollins3/fill_container/assets/73137934/7538f8ab-b2db-4869-bfdd-ddc17d67a915

[7:16pm]
