### ISSUE TITLE
webpack / EC2 deployment 👍 install fest works local 👎 !work deployment [12:49pm]

### ISSUE THREAD

**Issue by frankcollins3** [frankcollins3/fill_container#260]
express-graphql impeding install 
```
npm ERR! While resolving: express-graphql@0.12.0
npm ERR! Found: graphql@16.6.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^16.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
**npm ERR! peer graphql@"^14.7.0 || ^15.3.0" from express-graphql@0.12.0
npm ERR! node_modules/express-graphql
npm ERR!   express-graphql@"^0.12.0" from the root project
npm ERR!**
npm ERR! Conflicting peer dependency: graphql@15.8.0
npm ERR! node_modules/graphql
npm ERR!   peer graphql@"^14.7.0 || ^15.3.0" from express-graphql@0.12.0
npm ERR!   node_modules/express-graphql
npm ERR!     express-graphql@"^0.12.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/ubuntu/.npm/eresolve-report.txt for a full report.
```

**Comment by frankcollins3** [comment]
```
[1] sh: 1: nodemon: not found
[1] npm run server exited with code 127
[0] [webpack-cli] Failed to load '/home/ubuntu/fill_container/webpack.config.js' config
[0] [webpack-cli] Error: Cannot find module 'os-browserify/browser'
[0] Require stack:
[0] - /home/ubuntu/fill_container/webpack.config.js
[0] - /home/ubuntu/fill_container/node_modules/webpack-cli/lib/webpack-cli.js
[0] - /home/ubuntu/fill_container/node_modules/webpack-cli/lib/bootstrap.js
[0] - /home/ubuntu/fill_container/node_modules/webpack-cli/bin/cli.js
[0] - /home/ubuntu/fill_container/node_modules/webpack/bin/webpack.js
[0]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
[0]     at Function.resolve (node:internal/modules/cjs/helpers:114:19)
[0]     at Object.<anonymous> (/home/ubuntu/fill_container/webpack.config.js:29:19)
[0]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[0]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[0]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[0]     at Module.require (node:internal/modules/cjs/loader:1100:19)
[0]     at require (node:internal/modules/cjs/helpers:108:18)
[0]     at WebpackCLI.tryRequireThenImport (/home/ubuntu/fill_container/node_modules/webpack-cli/lib/webpack-cli.js:223:30) {
[0]   code: 'MODULE_NOT_FOUND',
[0]   requireStack: [
[0]     '/home/ubuntu/fill_container/webpack.config.js',
[0]     '/home/ubuntu/fill_container/node_modules/webpack-cli/lib/webpack-cli.js',
[0]     '/home/ubuntu/fill_container/node_modules/webpack-cli/lib/bootstrap.js',
[0]     '/home/ubuntu/fill_container/node_modules/webpack-cli/bin/cli.js',
[0]     '/home/ubuntu/fill_container/node_modules/webpack/bin/webpack.js'
[0]   ]
[0] }
```

👍 npm i os-browserify/browser --legacy-peer-deps 

npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/os-browserify/browser.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:


👍 npm i ${module} **--legacy-peer-deps** 

--legacy-peer-deps flag bringing success in allowing modules to be installed from:
ubuntu ${ip address} {my_app} :$ 

[12:53pm]
